---
- name: Quick webserver install and configuration
  hosts: 192.168.100.5 
  become: true
  tasks:
  - name: install apache and php packages for Ubuntu 
    package:
      name: 
        - "{{ apache_package }}" 
        - "{{ php_package }}"
      state: latest
      update_cache: yes
