---
- name: Quick webserver install and configuration
  hosts: 192.168.100.5 
  become: true
  tasks:
  - name: update repo index
    apt:
      update_cache: yes
  - name: Quick webserver install and configuration
    apt:
      name: apache2
      state: absent 
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
